# config.py
import os

# KAFKA_BOOTSTRAP_SERVER = "kafka:9092" #local development
KAFKA_BOOTSTRAP_SERVER="kafka:19092" #DNS development

API_KEY = os.getenv("FINNHUB_API_KEY")
SYMBOLS = ['BINANCE:ETHUSDT','BINANCE:BTCUSDT','BINANCE:SOLUSDT','BINANCE:ADAUSDT','BINANCE:XRPUSDT']