{
 "title": "Market Data",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ds", "query": "grafana-clickhouse-datasource" }
  ]
 },
 "panels": [
  {
   "title": "Current ETH Price",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "(\r\n  SELECT\r\n    timestamp AS time,\r\n    price\r\n  FROM ticks_db\r\n  WHERE $__timeFilter(timestamp)\r\n  ORDER BY time ASC\r\n  LIMIT 1\r\n)\r\nUNION ALL\r\n(\r\n  SELECT\r\n    timestamp AS time,\r\n    price\r\n  FROM ticks_db\r\n  WHERE $__timeFilter(timestamp)\r\n  ORDER BY time DESC\r\n  LIMIT 1\r\n);\r\n"
    }
   ]
  },
  {
   "title": "ETH Price Time Series",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfInterval(\r\n    timestamp,\r\n    INTERVAL toUInt32($__interval_ms * 5) MILLISECOND\r\n  ) AS time,\r\n  avg(price) AS price\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Volume ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(volume) AS total_vol\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\n"
    }
   ]
  },
  {
   "title": "Volume (USD)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(volume * price) AS total_vol_usd\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\n"
    }
   ]
  },
  {
   "title": "Market Data Table",
   "type": "table",
   "gridPos": { "h": 18, "w": 4, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  price,\r\n  volume,\r\n    toStartOfInterval(\r\n    timestamp,\r\n    INTERVAL toUInt32($__interval_ms * 5) MILLISECOND\r\n  ) AS time\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY time DESC\r\nLIMIT 100\r\n"
    }
   ]
  },
  {
   "title": "ETH OHLCV Time Series",
   "type": "candlestick",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfInterval(\r\n    timestamp,\r\n    INTERVAL toUInt32($__interval_ms * 25) MILLISECOND\r\n  ) AS time,\r\n    any(price) AS open,\r\n    anyLast(price) AS close,\r\n    max(price) AS high,\r\n    min(price) AS low\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "ETH Volume Time Series",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfInterval(\r\n    timestamp,\r\n    INTERVAL toUInt32($__interval_ms * 10) MILLISECOND\r\n  ) AS time,\r\n  sum(volume) as volume\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    }
   ]
  }
 ]
}