{
 "title": "Market Data",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current ETH Price",
   "type": "stat",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  price\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Min ETH Price",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  price\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "ETH Price Time Series",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 14, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfInterval(\r\n    timestamp,\r\n    INTERVAL toUInt32($__interval_ms * 5) MILLISECOND\r\n  ) AS time,\r\n  avg(price) AS price\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Max ETH Price",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  price\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "ETH Price Data Snippet",
   "type": "table",
   "gridPos": { "h": 26, "w": 7, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfInterval(\r\n    timestamp,\r\n    INTERVAL toUInt32($__interval_ms * 5) MILLISECOND\r\n  ) AS time,\r\n  symbol,\r\n  price,\r\n  volume\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY time DESC\r\n"
    }
   ]
  },
  {
   "title": "ETH OHLCV Time Series",
   "type": "candlestick",
   "gridPos": { "h": 15, "w": 14, "x": 8, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfInterval(\r\n    timestamp,\r\n    INTERVAL toUInt32($__interval_ms * 10) MILLISECOND\r\n  ) AS time,\r\n    any(price) AS open,\r\n    anyLast(price) AS close,\r\n    max(price) AS high,\r\n    min(price) AS low\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "ETH Volume Time Series",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 8, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfInterval(\r\n    timestamp,\r\n    INTERVAL toUInt32($__interval_ms * 10) MILLISECOND\r\n  ) AS time,\r\n  sum(volume) as volume\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    }
   ]
  }
 ]
}