{
 "title": "Pipeline Health",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "24hr Pipeline Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=\"http://pipeline:8001/health\"}[24h]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "1hr Pipeline Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=\"http://pipeline:8001/health\"}[1h]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5m Pipeline Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=\"http://pipeline:8001/health\"}[5m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Start/Stop Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT *\r\nFROM monitoring_db\r\nWHERE message LIKE 'System%'\r\nORDER BY monitoring_timestamp DESC"
    }
   ]
  },
  {
   "title": "Lag Anomalies",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT *\r\nFROM monitoring_db\r\nWHERE message NOT LIKE 'System%'\r\nORDER BY monitoring_timestamp DESC"
    }
   ]
  },
  {
   "title": "24hr Kafka Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=\"kafka:9092\"}[24h]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "24hr Clickhouse Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=\"http://clickhouse:8123/ping\"}[24h]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "24hr Websocket Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=\"ws.finnhub.io:443\"}[24h]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"pipeline\"} | pattern `<time> | <level> | <logger> | <msg>`"
    }
   ]
  },
  {
   "title": "Ticks / Min",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    toStartOfMinute(timestamp) AS minute,\r\n    sum(volume) AS ticksPerMinute\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY minute\r\nORDER BY minute;"
    }
   ]
  },
  {
   "title": "Ticks Per Minute Time Series",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfInterval(\r\n    timestamp,\r\n    INTERVAL toUInt32($__interval_ms * 25) MILLISECOND\r\n  ) AS time,\r\n  sum(volume) AS ticks\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY time\r\nORDER BY time;\r\n"
    }
   ]
  },
  {
   "title": "Avg Websocket Lag (Seconds)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    toStartOfMinute(avg_timestamp) AS minute,\r\n    avg(avg_websocket_lag) AS websocket_lag\r\nFROM websocket_diagnostics\r\nWHERE $__timeFilter(avg_timestamp)\r\nGROUP BY minute\r\nORDER BY minute;"
    }
   ]
  },
  {
   "title": "Websocket Lag Time Series",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfInterval(\r\n    avg_timestamp,\r\n    INTERVAL toUInt32($__interval_ms * 15) MILLISECOND\r\n  ) AS time,\r\n  avg(avg_websocket_lag) AS websocket_lag\r\nFROM websocket_diagnostics\r\nWHERE $__timeFilter(avg_timestamp)\r\nGROUP BY time\r\nORDER BY time;\r\n"
    }
   ]
  },
  {
   "title": "Warning Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 20 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"pipeline\"} |= \"WARNING\""
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 20 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"pipeline\"} |= \"WARNING\""
    }
   ]
  },
  {
   "title": "Avg Processing Lag (Seconds)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    toStartOfMinute(avg_timestamp) AS minute,\r\n    avg(avg_processing_lag) AS processing_lag\r\nFROM processing_diagnostics\r\nWHERE $__timeFilter(avg_timestamp)\r\nGROUP BY minute\r\nORDER BY minute;"
    }
   ]
  },
  {
   "title": "Processing Lag Time Series",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfInterval(\r\n    avg_timestamp,\r\n    INTERVAL toUInt32($__interval_ms * 15) MILLISECOND\r\n  ) AS time,\r\n  avg(avg_processing_lag) AS processing_lag\r\nFROM processing_diagnostics\r\nWHERE $__timeFilter(avg_timestamp)\r\nGROUP BY time\r\nORDER BY time;\r\n"
    }
   ]
  },
  {
   "title": "Cloud Upload Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"pipeline\"} |= \"Uploaded\""
    }
   ]
  }
 ]
}