{
 "title": "Pipeline Monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ds_clickhouse", "query": "grafana-clickhouse-datasource" },
   { "name": "ds_loki", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Ticks / Min",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    toStartOfMinute(timestamp) AS minute,\r\n    count(timestamp) AS ticksPerMinute\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY minute\r\nORDER BY minute DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Ticks Per Minute Time Series",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 2, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfInterval(\r\n    timestamp,\r\n    INTERVAL toUInt32($__interval_ms * 20) MILLISECOND\r\n  ) AS time,\r\n  count(timestamp) AS ticks\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY time\r\nORDER BY time;\r\n"
    }
   ]
  },
  {
   "title": "Websocket Lag (Seconds)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    toStartOfMinute(avg_timestamp) AS minute,\r\n    avg(avg_websocket_lag) AS websocket_lag\r\nFROM websocket_diagnostics\r\nWHERE $__timeFilter(avg_timestamp)\r\nGROUP BY minute\r\nORDER BY minute DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Websocket Lag Time Series",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfInterval(\r\n    avg_timestamp,\r\n    INTERVAL toUInt32($__interval_ms * 15) MILLISECOND\r\n  ) AS time,\r\n  avg(avg_websocket_lag) AS websocket_lag\r\nFROM websocket_diagnostics\r\nWHERE $__timeFilter(avg_timestamp)\r\nGROUP BY time\r\nORDER BY time;\r\n"
    }
   ]
  },
  {
   "title": "Processing Lag (Seconds)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    toStartOfMinute(avg_timestamp) AS minute,\r\n    avg(avg_processing_lag) AS processing_lag\r\nFROM processing_diagnostics\r\nWHERE $__timeFilter(avg_timestamp)\r\nGROUP BY minute\r\nORDER BY minute DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Processing Lag Time Series",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfInterval(\r\n    avg_timestamp,\r\n    INTERVAL toUInt32($__interval_ms * 15) MILLISECOND\r\n  ) AS time,\r\n  avg(avg_processing_lag) AS processing_lag\r\nFROM processing_diagnostics\r\nWHERE $__timeFilter(avg_timestamp)\r\nGROUP BY time\r\nORDER BY time;\r\n"
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"pipeline\"} | pattern `<time> | <level> | <logger> | <msg>`",
     "maxLines": 500
    }
   ]
  },
  {
   "title": "Cloud Upload Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"pipeline\"} |= \"Uploaded\"",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "Warning Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"pipeline\"} |= \"WARNING\"",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"pipeline\"} |= \"WARNING\"",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "Lag Anomalies",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT *\r\nFROM monitoring_db\r\nWHERE message NOT LIKE 'System%'\r\nORDER BY monitoring_timestamp DESC\r\nLIMIT 100"
    }
   ]
  },
  {
   "title": "System Start/Stop Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT *\r\nFROM monitoring_db\r\nWHERE message LIKE 'System%'\r\nORDER BY monitoring_timestamp DESC\r\nLIMIT 100"
    }
   ]
  }
 ]
}