{
 "title": "Server Monitoring",
 "description": "Prometheus Blackbox Exporter - latency + up/down list",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "target",
    "label": "target",
    "query": "label_values(probe_success, instance)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "nodename",
    "label": "Nodename",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},nodename)"
    }
   },
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\", nodename=\"$nodename\"},instance)"
    }
   },
   { "name": "ds_prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Server Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$node\",job=\"$job\"} - node_boot_time_seconds{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "stat",
   "description": "Overall Disk Space used",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{instance=\"$node\", job=\"$job\", device!~\"rootfs\"})\r\n - sum(node_filesystem_avail_bytes{instance=\"$node\", job=\"$job\", device!~\"rootfs\"}))\r\n / sum(node_filesystem_size_bytes{instance=\"$node\", job=\"$job\", device!~\"rootfs\"}) * 100\r\n"
    }
   ]
  },
  {
   "title": "Disk Space Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (\r\n  node_filesystem_size_bytes{device=\"/dev/vda1\", fstype=\"ext4\"}\r\n) / 3\r\n"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "stat",
   "description": "Overall CPU busy percentage (averaged across all cores)",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$node\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Disk Space Used ",
   "type": "timeseries",
   "description": "Percentage of filesystem space used.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{instance=\"$node\", job=\"$job\", device!~\"rootfs\"})\r\n - sum(node_filesystem_avail_bytes{instance=\"$node\", job=\"$job\", device!~\"rootfs\"}))\r\n / sum(node_filesystem_size_bytes{instance=\"$node\", job=\"$job\", device!~\"rootfs\"}) * 100\r\n",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$node\"}[$__rate_interval])))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "max by (instance) (probe_success{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Global Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}