{
 "title": "Real Time Market Data Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current ETH Price",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  price\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Max ETH Price",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  price\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "ETH Price Data Snippet",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfInterval(\r\n    timestamp,\r\n    INTERVAL toUInt32($__interval_ms * 5) MILLISECOND\r\n  ) AS time,\r\n  symbol,\r\n  price,\r\n  volume,\r\n  insert_time\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY time DESC\r\n"
    }
   ]
  },
  {
   "title": "24hr Pipeline Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=\"http://pipeline:8001/health\"}[24h]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "1hr Pipeline Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=\"http://pipeline:8001/health\"}[1h]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5m Pipeline Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=\"http://pipeline:8001/health\"}[5m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "24hr Kafka Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=\"kafka:9092\"}[24h]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "24hr Clickhouse Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=\"http://clickhouse:8123/ping\"}[24h]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "24hr Websocket Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=\"ws.finnhub.io:443\"}[24h]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min ETH Price",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  price\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Ticks / Min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    toStartOfMinute(timestamp) AS minute,\r\n    sum(volume) AS ticksPerMinute\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY minute\r\nORDER BY minute;"
    }
   ]
  },
  {
   "title": "Avg Websocket Lag (Seconds)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    toStartOfMinute(avg_timestamp) AS minute,\r\n    avg(avg_websocket_lag) AS websocket_lag\r\nFROM websocket_diagnostics\r\nWHERE $__timeFilter(avg_timestamp)\r\nGROUP BY minute\r\nORDER BY minute;"
    }
   ]
  },
  {
   "title": "Avg Processing Lag (Seconds)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    toStartOfMinute(avg_timestamp) AS minute,\r\n    avg(avg_processing_lag) AS processing_lag\r\nFROM processing_diagnostics\r\nWHERE $__timeFilter(avg_timestamp)\r\nGROUP BY minute\r\nORDER BY minute;"
    }
   ]
  },
  {
   "title": "Ticks Per Minute Time Series",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfInterval(\r\n    timestamp,\r\n    INTERVAL toUInt32($__interval_ms * 25) MILLISECOND\r\n  ) AS time,\r\n  sum(volume) AS ticks\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY time\r\nORDER BY time;\r\n"
    }
   ]
  },
  {
   "title": "Websocket Lag Time Series",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfInterval(\r\n    avg_timestamp,\r\n    INTERVAL toUInt32($__interval_ms * 15) MILLISECOND\r\n  ) AS time,\r\n  avg(avg_websocket_lag) AS websocket_lag\r\nFROM websocket_diagnostics\r\nWHERE $__timeFilter(avg_timestamp)\r\nGROUP BY time\r\nORDER BY time;\r\n"
    }
   ]
  },
  {
   "title": "Processing Lag Time Series",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfInterval(\r\n    avg_timestamp,\r\n    INTERVAL toUInt32($__interval_ms * 15) MILLISECOND\r\n  ) AS time,\r\n  avg(avg_processing_lag) AS processing_lag\r\nFROM processing_diagnostics\r\nWHERE $__timeFilter(avg_timestamp)\r\nGROUP BY time\r\nORDER BY time;\r\n"
    }
   ]
  },
  {
   "title": "ETH Price Time Series",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfInterval(\r\n    timestamp,\r\n    INTERVAL toUInt32($__interval_ms * 5) MILLISECOND\r\n  ) AS time,\r\n  avg(price) AS price\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "System Start/Stop Events",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT *\r\nFROM monitoring_db\r\nWHERE message LIKE 'System%'\r\nORDER BY monitoring_timestamp DESC"
    }
   ]
  },
  {
   "title": "Lag Anomalies",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT *\r\nFROM monitoring_db\r\nWHERE message NOT LIKE 'System%'\r\nORDER BY monitoring_timestamp DESC"
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 5, "x": 12, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"pipeline\"} | pattern `<time> | <level> | <logger> | <msg>`"
    }
   ]
  },
  {
   "title": "Warning Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"pipeline\"} |= \"WARNING\"\r\n"
    }
   ]
  },
  {
   "title": "ETH OHLCV Time Series",
   "type": "candlestick",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfInterval(\r\n    timestamp,\r\n    INTERVAL toUInt32($__interval_ms * 10) MILLISECOND\r\n  ) AS time,\r\n    any(price) AS open,\r\n    anyLast(price) AS close,\r\n    max(price) AS high,\r\n    min(price) AS low\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"pipeline\"} |= \"ERROR\"\r\n"
    }
   ]
  },
  {
   "title": "Cloud Upload Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 30 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"pipeline\"} |= \"Uploaded\"\r\n"
    }
   ]
  },
  {
   "title": "ETH Volume Time Series",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfInterval(\r\n    timestamp,\r\n    INTERVAL toUInt32($__interval_ms * 10) MILLISECOND\r\n  ) AS time,\r\n  sum(volume) as volume\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    }
   ]
  }
 ]
}